### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by pettinger** [fuzziebrain/orclapex-autocomplete#1]
Godd morning,

i am a kind of newbish in using visual code. pls give me a hint how to install the plugin mamually

thanks
peter

**Comment by fuzziebrain** [comment]
Hi Peter,

The instructions was posted in the release notes, but it isn't too obvious and I apologise. I have now published the 0.0.1 release, so you can pick it up from the VSC Marketplace. Search for `orclapex` and you should find it. If not, please let me know.

**Comment by pettinger** [comment]
Working great, Thanks
